FROM python:3.10.13-slim-bullseye
ENV WORKSPACE_DIR "/workspace"
# Install the xz-utils package
RUN apt-get update
COPY requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install -r ./requirements.txt


