version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/.ssh:/home/vscode/.ssh
      - .:/workspace:cached
    command: sleep infinity
